---
title: "My English activity log"
description: |
  These are activities that I do to improve my skills in English
author:
  - name: Marine Thirion
date: 09-29-2019
preview: English.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Week 5**  
This week I started to watch a new serie in English with the english subtitles. Sometimes I try to understand without it but that's difficult to me to hear all the words. 
I also watched free scientifics courses on a website called "Khan academy", you can learn a lot of things on a lot of subjetcs.  

**Week 6**
This week I've continued to watch my series on Netflix *BatesMotel* and I have put *The Big Bang Theory* in English and I thought that jokes was really better ; French traduction is sometimes such a mess. I've read biological articles on plants and that was really interesting. I've also watched YouTube videos of American humorist  

**Week 7**
I started to play videogames on Nintendo Switch like Skyrim and I've put all the game in English. It's a really good game and graphisms are amazing, people who realized it were really talented. I've decided to watch *Stranger things* in English and I've watched American videoes on YouTube. I've also helped my little sister with her homeworks in English, she has 12 years old and so she is learning the basics of this language.  

**Week 8** 
This week was really productive in English because I read a lot of biological article on scientific website. I like to learn everyday what happened in the scientific world. I had a lot of traject in train to go to school so I listened to a lot of English music, I like artists like *Imagine Dragons*, *Billie Eilish*, *Ed Sheeran* and so on. I tried to understand all the lyrics just in listening

**Week 9**
This week I did a lot to improve my reading skills in English. Every Sunday I like to go to flea market and I found a good classical book in English : *Alice in wonderland* from Lewis Carroll, I spent a good time in reading it. I also continued to play at Skyrim in English and had a lot of fun
