---
title: "Article 5 : What's the story, morning glory? Taxonomy, evolution and sweet potatoes"
author:
  - name: Marine Thirion
date: 12-13-2019
preview: article5.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Article 
## Source of the article 

[https://phys.org/news/2019-11-story-morning-glory-taxonomy-evolution.html](https://phys.org/news/2019-11-story-morning-glory-taxonomy-evolution.html)

More information: *Nature Plants (2019)*. DOI: 10.1038/s41477-019-0535-4  
Journal information: *Nature Plants *  
Image: Valley creeper 3 from Bolivia 1 of 850 species of morning glory distributed throughout the tropics. Credit: JRI Wood  
date: 11/11/19
word count: 664 words


# Analysis of the article 
## Vocabulary

| Word from the text   | Synonym/definition   | French translation   |
|:--------------------:|:--------------------:|:--------------------:|
| morning glory   | the common name for over 1,000 species of flowering plants in the family Convolvulaceae, whose current taxonomy and systematics are in flux. | Ipomoea tricolor |
| root     | the part of a plant which attaches it to the ground or to a support, typically underground, conveying water and nourishment to the rest of the plant via numerous branches and fibres | racine  |
| solely   | only   | seulement  |
| insight   | profond perception  | connaissance approfondie   |
| edible    | can be eaten   | comestible    |
| comsuption   | the action of using up a resource  | consommation  |
| hinder  | slow progress   | entraver |
| backlog   | unprocessed items   | retard   |
| bulk of  | greater part    | la majeure partie de |
| pertain to   | relate   | concerner   |
| feasible   | realistic   | vraisemblable   |
| underpin  | support   | étayer   |


## Analysis table 

|                                |                                  |
|:------------------------------:|----------------------------------|
| Researchers        | University of Oxford's Department of Plant Sciences      |
| Published in ?  | *Nature plants* on the 11/11/19  |
| General topic    | The biggest study of the morning glories which also contributes  to the taxonomy and evolution of this megadiverse group of plants |
| Procedure     | The researchers led the first study of the morning glories at a global scale, they described 63 new species and indentified of a large number of synonyms. They used dried plants preserved and analyze their morphology and their molecules to compare them |
| Conclusion/discovery    | As previously thought, the storage root was an already-existing trait that predisposed the plant for cultivation and not just the result of human domestication/ Sweet potato is not the only species of morning glory that produces storage roots |
| Remaining questions   | Scientists have to do an up-to-date taxonomy to stop the biodiversity crisis. |

